spring:
    jpa:
        hibernate.ddl-auto: none
        use-new-id-generator-mappings: true
    datasource:
        url: '${DB_URL}'
        username: '${DB_USER}'  
        password: '${DB_PASS}'
    thymeleaf:
        mode: LEGACYHTML5  
        cache: false  
    batch:
        job.enabled: false
        initializer.enabled: true
      
